title:            How can I do it?
description:      How can I do it in...!.
disqus_shortname: ebbypeter
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://howcanidoit.in

#http://howcanidoit.in
#http://localhost:4000

# Owner/author information
owner:
  name:           Ebby Peter
  avatar:         Ebby.jpg
  bio:            "A developer who specializes in SharePoint, WPF, MVC, Windows 8 and Windows Phone Apps; who loves to experiment and learn something new each day, every day."
  email:          ebby.learning@outlook.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: EbbyPeter       
  facebook: EbbyPeter      
  github: EbbyPeter         
  stackexchange: 
  linkedin: EbbyPeter      
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  # google plus id, include the '+', eg +mmistakes
  google_plus: +EbbyPeter1

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-56540581-1 
google_verify: 3-GDL4XGJW3KBT2jaHvr0MXkkiaEHd6JTfLSKjPj3gs     
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: 61E4F53D58574CE42FCF77D16F95C06D    

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Pacific/Auckland
future:      true
highlighter: pygments
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# Amount of post to show on home page
paginate: 10

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]